version: '3'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: nextApp.Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: server.Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network

networks:
  app-network: